# _config.yml

title: L.A. Young - Soul in Full Color
email: your-email@example.com
description: >-
  Soul singer blending jazz, blues, funk, hip-hop, and country.
baseurl: "/LAYoungBandPage"
url: "https://djmochajava-lang.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - index.html