# _config.yml

# Welcome to Jekyll!
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Site settings
title: L.A. Young - Soul in Full Color
email: your-email@example.com
description: >-
  Soul singer blending jazz, blues, funk, hip-hop, and country.
baseurl: "/LAYoungBandPage"
url: "https://djmochajava-lang.github.io"
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Suppress SASS deprecation warnings
sass:
  quiet_deps: true

# Exclude from processing
exclude:
  - index.html